before:
  hooks:
    - go mod tidy

builds:
  - id: sql-exporter
    binary: sql-exporter
    env:
      - CGO_ENABLED=0
    main: .
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - windows
      - darwin
